### ISSUE TITLE
Как правильно идентифицировать PaymentModel? 

### ISSUE THREAD

**Issue by vitramir** [izatop/cloudpayments#11]
В результате вызова методов оплаты приходит ответ типа 
```typescript
type PaymentResponse = PaymentSuccessResponse | PaymentFailedResponse | Payment3DSResponse;
```

внутри Model типа
```typescript
PaymentSuccessModel | PaymentModel | Payment3DSModel;
```

Как отличить Payment3DSModel от PaymentModel?
В пакете есть готовые функции, которые позволяют проверить тип интерфейса?

**Comment by izatop** [comment]
Добрый день. Можно идентифицировать результат по соответствующим полям. Вы можете самостоятельно написать небольшую обертку, которая будет добавлять поле с типом ответа в результирующий объект. В принципе я и сам могу добавить такой функционал в пакет, но это займет некоторое время.

**Comment by vitramir** [comment]
У них единственное общее поле TransactionID. Соответственно Typescript не дает обратиться к другим полям. Я просто хотел уточнить, что нет никаких готовых функций вроде isSuccessModel, которые бы возвращали правильный тип модели.
Я тогда добавлю самостоятельно эту логику. PR скину.

**Comment by izatop** [comment]
У результата ответа `Response` любого метода API клиента  есть метод `isSuccess()`. Давайте я вам пример дам, как можно отличить какой именно ответ был от клиента:

```typescript
const service = new ClientService(options);

function isPayment3DSModel(model: any): model is Payment3DSModel {
    return typeof model === "object"
        && "TransactionId" in model
        && "PaReq" in model
        && "AcsUrl" in model;
}

const clientApi = service.getClientApi();
const data = await clientApi.chargeCryptogramPayment({} as any);
if (data.isSuccess()) {
    const {Model} = data.getResponse();
    if (isPayment3DSModel(Model)) {
        // Model.AcsUrl now available;
    }
}
```

**Comment by izatop** [comment]
Перед тем как делать PR, давайте обсудим каким путем лучше добавить этот функционал.

**Comment by vitramir** [comment]
Да, эту функцию я и искал, только внутри пакета.

**Comment by izatop** [comment]
В идеале надо бы добавить метод` Response.getModel()` который будет возвращать объект с полями `kind` (например `PaymentSuccessResponse`) и `data` содержащий данные поля `Model` ответа сервиса соответствующего типа.

**Comment by vitramir** [comment]
Такое изменение не будет обратно совместимым. 

Я вижу три union'а.
- PaymentResponse = PaymentSuccessResponse
    | PaymentFailedResponse
    | Payment3DSResponse

- PayoutResponse = PayoutSuccessResponse | PayoutFailedResponse

- HistoryPaymentModel = PaymentModel | PaymentSuccessModel

Для `PaymentResponse` было бы удобно
```typescript
if(!response.isSuccess()){
//response.model of type PaymentModel
}else if(response.is3DS()){
   //response.model of type Payment3DSModel
}else{
  //response.model of type PaymentSuccessModel
}
```

Для `PayoutResponse` аналогично.

Для `HistoryPaymentModel`  такое не подходит. Есть ли какой-то явный признак в `PaymentModel` показывающий, что это `PaymentSuccessModel`?

**Comment by vitramir** [comment]
Да, ошибся на счет обратной совместимости. Все ок.

**Comment by izatop** [comment]
Сейчас все будет. Я придумал несколько извращенный способ, но он будет самым совместимым и typesafe.

**Comment by vitramir** [comment]
На сколько извращенный? :)
Вы какое-то отношение к Cloudpayments имеете или сторонний разработчик?

**Comment by izatop** [comment]
Ну что-то вроде такого:

```typescript
const service = new ClientService(options);
const clientApi = service.getClientApi();
const response = await clientApi.chargeCryptogramPayment(request);
const data = response.transform(TransformPaymentResponse);
if (data.kind === "Payment3DS") {
    // do something with data.data...
}
```

Нет, я сторонний разработчик, но мы пользуемся их системой для проведения платежей. Поэтому этот пакет я разрабатываю и поддерживаю.

**Comment by vitramir** [comment]
После вызова chargeCryptogramPayment мы уже знаем что это PaymentResponse, поэтому лишнее действие в виде `transform(TransformPaymentResponse)` не хотелось бы применять.
На счет моего варианта что скажете?

**Comment by izatop** [comment]
К сожалению невозможно использовать type guard функцию для изменения типа внутри объекта вызывающего метод. Поэтому тут несколько вариантов и один из них через трансформацию (теоретически можно не передавать в transform класс трансформера, а сделать это заранее внутри метода API). Второй способ, это вынести в какой-то статический класс методы для проверки типа и передавать внутрь них Response для фильтрации типа внутри условия.

**Comment by vitramir** [comment]
```typescript
class PaymentResponseClass<T extends PaymentResponse> extends Response<T> {
  isSuccess(): this is PaymentSuccessResponseClass {
    return super.isSuccess();
  }
  is3DS(): this is Payment3DSResponseClass {
    return false; //TODO
  }
}

class PaymentSuccessResponseClass extends PaymentResponseClass<
  PaymentSuccessResponse
> {}
class PaymentFailResponseClass extends PaymentResponseClass<
  PaymentFailedResponse
> {}
class Payment3DSResponseClass extends PaymentResponseClass<
  Payment3DSResponse
> {}

const getResponse = i => {
  switch (i) {
    case 1:
      return new PaymentSuccessResponseClass({});
    case 2:
      return new Payment3DSResponseClass({});
    default:
      return new PaymentFailResponseClass({});
  }
};

let resp = getResponse(1);
//resp of type PaymentSuccessResponseClass | Payment3DSResponseClass | PaymentFailResponseClass

if (resp.isSuccess()) {
  resp.getResponse().Model.AuthCode;
} else if (resp.is3DS()) {
  resp.getResponse().Model.AcsUrl;
} else {
  resp.getResponse().Model;
}
```

**Comment by izatop** [comment]
Да, вариант.

**Comment by vitramir** [comment]
А что на счет HistoryPaymentModel? PaymentModel.Status позволяет понять, что это PaymentSuccessModel?

**Comment by vitramir** [comment]
Даже вот так, чтобы лишние классы не лепить

```typescript
class PaymentResponseClass<T extends PaymentResponse> extends Response<T> {
  isSuccess(): this is PaymentResponseClass<PaymentSuccessResponse> {
    return super.isSuccess();
  }
  is3DS(): this is PaymentResponseClass<Payment3DSResponse> {
    return false; //TODO
  }
}

let resp = new PaymentResponseClass<PaymentResponse>({});

if (resp.isSuccess()) {
  resp.getResponse().Model.AuthCode;
} else if (resp.is3DS()) {
  resp.getResponse().Model.AcsUrl;
} else {
  resp.getResponse().Model;
}
```

**Comment by izatop** [comment]
Да я так и сделал.

**Comment by izatop** [comment]
Не, косяк. Есть мысли как заставить правильно типы резолвить TS в таком исполнении:

```typescript
class PaymentResponseClass<T extends PaymentResponse> extends ClientResponse<T> {
        isPaymentSuccessResponse(): this is PaymentResponseClass<PaymentSuccessResponse> {
            return this.isSuccess();
        }
        is3DS(): this is PaymentResponseClass<Payment3DSResponse> {
            return false; //TODO
        }
    }

    async function fetch() {
        return new PaymentResponseClass<PaymentResponse>({} as any);
    }
    
    const resp = await fetch();
    if (resp.isSuccess()) {
        resp.getResponse().Model.AuthCode;
    } else if (resp.is3DS()) {
        resp.getResponse().Model.AcsUrl;
    } else {
        resp.getResponse().Model;
    }
```

**Comment by vitramir** [comment]
```diff
async function fetch() {
    return new PaymentResponseClass<PaymentResponse>({} as any);
}

const resp = await fetch();
- if (resp.isSuccess()) {
+ if (resp.isPaymentSuccessResponse()) {
    resp.getResponse().Model.AuthCode;
} else if (resp.is3DS()) {
    resp.getResponse().Model.AcsUrl;
} else {
```

С таким исправлением резолвит правильно

**Comment by izatop** [comment]
Я закомитил изменения, но пока не паблишил. Посмотри, если все ок, я опубликую. Если нет - пожелания, предложения и PR приветствуются.

P.S. Комментарий удалил, т.к. косяк был вообще в другом)

**Comment by vitramir** [comment]
```

**Comment by vitramir** [comment]
3ds это не success ответ
```diff
public isPayment3DSResponse(): this is PaymentWith3DSClientResponse<
    Payment3DSResponse
  > {
    const { Model } = this.getResponse();
    return (
-      this.isSuccess() && this.has(["TransactionId", "PaReq", "AcsUrl"], Model)
+      !this.isSuccess() && this.has(["TransactionId", "PaReq", "AcsUrl"], Model)
    );
  }
```

**Comment by vitramir** [comment]
Чем код отформатирован? Prettier переформатирует все у меня

**Comment by izatop** [comment]
Давно я в документацию не заглядывал. Поправил. Форматирование в этом проекте вебштормовское. Добавил tslint стандартный и editorconfig.

**Comment by izatop** [comment]
Оставил короче линтинг с eslint по рекомендациям для TypeScript. Prettier как-то криво цепляется и конфликтует (даже если как плагин к eslint).

**Comment by izatop** [comment]
Давай проверишь еще раз все и сделаем паблиш в репу npm'a.

**Comment by vitramir** [comment]
> Оставил короче линтинг с eslint по рекомендациям для TypeScript. Prettier как-то криво цепляется и конфликтует (даже если как плагин к eslint).

ok



> Давай проверишь еще раз все и сделаем паблиш в репу npm'a.

Пока все ок. Доделаю сегодня модуль и отпишусь.

**Comment by izatop** [comment]
Окей

**Comment by vitramir** [comment]
Есть пара вопросов еще:
1)Если я правильно понимаю, то вернуть ответ содержащий 3ds может только два метода: authorizeCryptogramPayment и chargeCryptogramPayment. Для остальных методов связанных с оплатой другой набор возможных ответов.
2)Не работает определение типа в else ветке условия. Сделал временно вот такой фикс, но хочется более красивое решение найти.

```typescript
type PaymentWith3DSClientResponseUnion =
  | PaymentWith3DSClientResponse<PaymentSuccessResponse>
  | PaymentWith3DSClientResponse<Payment3DSResponse>
  | PaymentWith3DSClientResponse<PaymentFailedResponse>;

export class ClientApi extends ClientRequestAbstract {
  public async chargeCryptogramPayment(data: CryptogramPaymentRequest) {
    return new PaymentWith3DSClientResponse<PaymentResponse>(
      await this.call<PaymentResponse>("/payments/cards/charge", data)
    ) as PaymentWith3DSClientResponseUnion;
  }
```

**Comment by izatop** [comment]
1. По идее 3DS должен всплывать при использовании криптограммы для оплаты без взаимодействия с виджетами CP. То есть при оплате заранее сохраненными данными карты в зашифрованном виде.

2. Не очень понял про else. Там же три состояния: а) успех; б) 3ds; в) ошибка. Пример можешь дать, что хочешь и что не выходит?

**Comment by vitramir** [comment]
1. Соответственно из остальных методов убираем PaymentWith3DSClientResponse? (confirm3DSPayment, authorizeTokenPayment, chargeTokenPayment)
2. Да вот все пример, который мы обсуждали

```typescript
if (resp.isSuccess()) {
  //правильный тип PaymentWith3DSClientResponse<PaymentSuccessResponse>
} else if (resp.is3DS()) {
  //правильный тип PaymentWith3DSClientResponse<Payment3DSResponse>
} else {
  //а здесь исходный тип класса PaymentWith3DSClientResponse<PaymentResponse>
  //должно быть PaymentWith3DSClientResponse<PaymentFailedResponse>
}
```

**Comment by izatop** [comment]
1. А вот надо посмотреть, с чего я вдруг туда это засунул. По токену может тоже может просить 3ds...
2. А, вот это можно сделать в принципе по дефолту просто.

**Comment by vitramir** [comment]
1. Точно может? В документации такого варианта ответа нет https://developers.cloudpayments.ru/#oplata-po-tokenu-rekarring

**Comment by izatop** [comment]
Да, я тоже посмотрел. Токен можно получить при оплате по криптограмме, соответственно, процедура 3ds или не нужна или уже пройдена. Сделаю фикс чуть позже.

**Comment by izatop** [comment]
Вот так вроде ближе к правде.

**Comment by vitramir** [comment]
1)Просмотр транзакции https://developers.cloudpayments.ru/#prosmotr-tranzaktsii
В документации ожидается массив. На деле приходит одна запись.

```diff
export type PaymentGetResponse = {
    Success: boolean;
    Message: null;
-    Model: HistoryPaymentModel[];
+    Model: HistoryPaymentModel;
};
```

2)Мы так и не договорились как определять тип HistoryPaymentModel. Наверное нужен метод в Model.

3)У меня часть методов всегда возвращает success=false. Например, просмотр или отмена транзакции. В документации написано, что должно быть true. Это расхождение с документацией или это только у меня так? Если расхождение, то может быть имеет смысл добавить другой способ для проверки, что запрос завершился успешно?

**Comment by vitramir** [comment]
Поправка по пункту 3. False приходит для транзакций, которые отклонены или отменены.

**Comment by izatop** [comment]
Интерфейс поправил. По ошибке в документации багу скинул разрабам (я думаю документацию поправят). Добавил `PaymentHistoryClientResponse` с методами для получения всех платежей, успешных и зафейленных. Посмотри и проверь, пожалуйста.

**Comment by vitramir** [comment]
Я у себя не использую пока нигде `getPaymentsList`. Я про метод `getPayment` говорил. Теперь для определения типа можно использовать метод `PaymentClientResponse.isPaymentSuccessResponse`. Оно, конечно, работает, но может было бы лучше из Model класс сделать и туда метод добавить?

Что на счет Success в ответе? Он зависит от состояния транзакции и CloudPayments это подтвердили. Может быть `ClientResponse.isSuccess` должен проверять `Message==null`?

**Comment by vitramir** [comment]
В общем внятного ответа от CloudPayments на тему success я не добился. Предложили смотреть на status. Предлагаю публиковать как есть. Хорошо бы только наверное добавить в readme информацию о наличии `PaymentClientResponse.isPaymentSuccessResponse`

**Comment by izatop** [comment]
> Теперь для определения типа можно использовать метод `PaymentClientResponse.isPaymentSuccessResponse`. Оно, конечно, работает, но может было бы лучше из Model класс сделать и туда метод добавить?

Можно добавить еще один тип респонса с проверкой isSuccess.

> Что на счет Success в ответе? Он зависит от состояния транзакции и CloudPayments это подтвердили. Может быть `ClientResponse.isSuccess` должен проверять `Message==null`?

Да, по-моему я понял о каком казусе идет речь. Есть ситуации с Success false и Message, типа внутренних ошибок сервиса или при передаче некорректных данных, а есть Success false с пустым сообщением и моделью, которая описывает данные транзакции.
Но тут с isSuccess думаю ситуацию менять нельзя, т.к. это breaking changes и может у кого-то сломать логику и в принципе эта проверка была изначально для проверки true/false соответствующего поля, чтобы в респонс не лезть. Возможно стоит добавить что-то вроде isSuccessResponse или isSuccessTransaction/isFailTransaction?

Да, документацию обновлю.

**Comment by vitramir** [comment]
> Можно добавить еще один тип респонса с проверкой isSuccess.

Тогда это не подойдет для методов, которые возвращают массив транзакций. Не всегда удобно получать их через два отдельных метода. Тут именно вопрос про изменение Model на класс и добавление туда метода. Может быть даже в response не нужны методы, которые были добавлены в рамках этого issue.

> Возможно стоит добавить что-то вроде isSuccessResponse или isSuccessTransaction/isFailTransaction? 

В этом вопросе я за isSuccessResponse. При чем я думаю надо добавить соответствующий тип FailedResponse, который не будет содержать Model. Соответственно результат запроса будет SuccessResponse | FailedResponse. Это заставит везде делать проверку на isSuccessResponse в коде и обрабатывать ошибки.

Могу добавить и то и другое, но хочу сначала согласовать этот момент.

**Comment by izatop** [comment]
> Тогда это не подойдет для методов, которые возвращают массив транзакций. Не всегда удобно получать их через два отдельных метода. Тут именно вопрос про изменение Model на класс и добавление туда метода. Может быть даже в response не нужны методы, которые были добавлены в рамках этого issue.

Я бы все же не хотел добавлять свою логику на данных в ответе от API. Я при разработке думал над тем, чтобы сделать свою обертку над данными, но решил, что лучше не брать эту функцию под ответственность библиотеки. В принципе не проблема написать свой трансформер или обертку какую-то, которая будет транслировать данные CP в нужный формат с необходимыми функциями для отдельных кейсов.



> В этом вопросе я за isSuccessResponse. При чем я думаю надо добавить соответствующий тип FailedResponse, который не будет содержать Model. Соответственно результат запроса будет SuccessResponse | FailedResponse. Это заставит везде делать проверку на isSuccessResponse в коде и обрабатывать ошибки.
> 
> Могу добавить и то и другое, но хочу сначала согласовать этот момент.

Да, я тоже смотрел в код и думал: а почему я не добавил отдельный тип FailedResponse? Не нашел ответа. Если сделаете PR - буду рад. А то сейчас времени нет поправить.

**Comment by vitramir** [comment]
Ок. Тогда предлагаю эту задачу закрывать. Публиковать версию. И FailedResponse уже отдельно сделаем.

**Comment by izatop** [comment]
Окей, опубликую и тогда закрою сразу. Доку только еще поправлю.

**Comment by vitramir** [comment]
Надо еще вот поправить
```diff
export class PayoutClientResponse<T extends PayoutResponse> extends ClientResponse<T> {
    public isPayoutSuccessResponse(): this is ClientResponse<PayoutSuccessResponse> {
        const { Model } = this.getResponse();
-       return this.isSuccess() && this.has(["TransactionId", "AuthCode"], Model);
+       return this.isSuccess() && PayoutClientResponse.has(["TransactionId", "AuthCode"], Model);
    }
}
```

**Comment by izatop** [comment]
Новая версия https://www.npmjs.com/package/cloudpayments
