### ISSUE TITLE
Wrong response codes for check notification

### ISSUE THREAD

**Issue by ashitikov** [izatop/cloudpayments#13]
Hello!

According to documentation: https://developers.cloudpayments.ru/#check
11 code means AccountId is wrong. However enum ResponseCodes states:
```
export declare enum ResponseCodes {
    SUCCESS = 0,
    UNKNOWN_INVOICE_ID = 10,
    INVALID_AMOUNT = 11,
    REJECTED = 13,
    EXPIRED = 20
}
```
I guess 11 should be INVALID_ACCOUNT_ID, while 12 should be INVALID_AMOUNT.
Thank you

**Comment by izatop** [comment]
Hi, it seems like what the codes have been changed. I think these changes may breaks something and i have published it in new major version.
