### ISSUE TITLE
parseRequest рассчитывает, что req это сырой nodejs http поток

### ISSUE THREAD

**Issue by dilame** [izatop/cloudpayments#3]
Любой фреймворк сначала дожидается получения данных, и только потом вызывает action. Получается, что я не могу использовать POST запросы для проверки нотификаций на любом из доступных NodeJS MVC фреймворков. В частности, я использую NestJS. И самое обидное - код нормально отрабатывает, без ошибок. Просто action бесконечно висит, так как событие end произошло раньше, чем началось выполнение.

Мне кажется, это огромная недоработка, и следует положить на плечи пользователя передачу заголовка и параметров в функцию. Ну или предусмотреть вариант, когда тело запроса уже получено. Никто в современном мире не пишет приложения, используя nodejs http модуль.

**Comment by izatop** [comment]
Я могу добавить вместо обработки сырого объекта IncomingMessage абстрактный механизм извлечения и проверки данных, который можно будет использовать как с IncomingMessage так и с передачей заранее подготовленного объекта. Но во втором случае можем ли мы гарантировать порядок следования полей при сериализации объекта в строку для проверки подписи по ключу?

**Comment by dilame** [comment]
Предполагаю, что универсальное решение будет непросто сделать. Я не подумал над тем, что мы не можем знать, что именно используется поверх http модуля. В любом случае придётся положить это на плечи юзера. При создании экземпляра ClientService можно дать возможность указать ключ, по которому в req лежит raw body, а как именно он там окажется - уже дело пользователя.
Сейчас я просто буду использовать GET.

**Comment by izatop** [comment]
Ну я сделал возможность передачи объекта в виде структуры

```js
type payload = IncomingMessage | {
  payload: object
  signature?: string
  headers?: any
}
```
Можно передать объект, он будет сериализован JSON.stringify, а подпись будет браться или из signature или из headers (которые должны быть получены из IncomingMessage). В принципе, могу так же добавить rawBody параметр туда же вместо payload.

**Comment by izatop** [comment]
А, ну вообще пусть payload будет string | object. Чуть позже новую версию запушу.

**Comment by izatop** [comment]
Сделал в f3bb134, версия 1.0.1 https://www.npmjs.com/package/cloudpayments

Интерфейс передачи кастомных данных вместо IncomingMessage:

```ts
interface NotificationCustomPayload {
    payload: object | string;
    headers?: any;
    signature?: string;
}
```
